### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by t-cool** [praharshjain/Electron-PDF-Viewer#2]
Hi.
I had a following error on macOS:

```
Uncaught Exception:
TypeError: Cannot read property 'app' of undefined
    at Object.<anonymous> (/Users/t-cool/Electron-PDF-Viewer/main.js:147:31)
    at Object.<anonymous> (/Users/t-cool/Electron-PDF-Viewer/main.js:238:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at loadApplicationPackage (/Users/t-cool/Electron-PDF-Viewer/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/Users/t-cool/Electron-PDF-Viewer/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:329:5)
    at Object.<anonymous> (/Users/t-cool/Electron-PDF-Viewer/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:366:3)
```

**Comment by praharshjain** [comment]
Thanks for reporting. Have added a fix for it. Check it out!

**Comment by t-cool** [comment]
Thank you for your update!
But I still have an error as below:

On Electron
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from null
    at App.<anonymous> (/Users/t-cool/Desktop/Electron-PDF-Viewer/main.js:181:18)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
```

On Terminal:
```
$ npm start

> Electron-PDF-Viewer@1.0.0 start /Users/t-cool/Desktop/Electron-PDF-Viewer
> electron .

2018-05-13 22:00:27.369 Electron[9071:735442] *** WARNING: Textured window <AtomNSWindow: 0x7ffd26e3eaf0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
^C$ npm install && npm start
up to date in 0.852s

> Electron-PDF-Viewer@1.0.0 start /Users/t-cool/Desktop/Electron-PDF-Viewer
> electron .

2018-05-13 22:01:37.901 Electron[9080:737293] *** WARNING: Textured window <AtomNSWindow: 0x7fee9816f3e0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

**Comment by praharshjain** [comment]
Fixed the null issue, can you test it now?

**Comment by t-cool** [comment]
Thank you for your update!
Now I can launch the app, but I cannot open a pdf file.
The key"Ctr/Cmd-o" doesn't work.

```
$ node -v
v8.9.3
$ npm -v
5.5.1
$ npm install && npm start
up to date in 0.81s

> Electron-PDF-Viewer@1.0.0 start /Users/t-cool/Desktop/Electron-PDF-Viewer-master
> electron .

2018-05-14 02:56:48.557 Electron[11901:882295] *** WARNING: Textured window <AtomNSWindow: 0x7fa43e56a5d0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

**Comment by praharshjain** [comment]
Have fixed the menu, should work now. The shortcut key 'Cmd+o' also works.

**Comment by t-cool** [comment]
Thank you for update!
Now I'm enjoying your pdf-reader!
